#define RESOURCE_INIT 500

/*歩兵*/
#define POWER_HOHEI 10
#define MAXHP_HOHEI 700
#define DEFENSE_HOHEI 1
#define SPEED_HOHEI 2
#define A_TYPE_HOHEI RAND
#define COST_HOHEI 0

#define CLK_HOHEI 50
#define A_FREQ_HOHEI 2

/*風船兵*/
#define POWER_BALLOON 120
#define MAXHP_BALLOON 800
#define DEFENSE_BALLOON 1
#define SPEED_BALLOON 2
#define A_TYPE_BALLOON RAND
#define COST_BALLOON 80
#define CLK_BALLOON 200
#define A_FREQ_BALLOON 90

/*ロボ兵*/
#define POWER_BIG 500
#define MAXHP_BIG 5000
#define DEFENSE_BIG 2
#define SPEED_BIG 1
#define A_TYPE_BIG RAND
#define COST_BIG 300
#define CLK_BIG 120
#define A_FREQ_BIG 150
/*神風兵*/
#define POWER_KAMIKAZE 600
#define MAXHP_KAMIKAZE 700
#define DEFENSE_KAMIKAZE 1
#define SPEED_KAMIKAZE 5
#define A_TYPE_KAMIKAZE SKY
#define COST_KAMIKAZE 500
#define CLK_KAMIKAZE 150
#define A_FREQ_KAMIKAZE 10
/*バズーカ兵*/
#define POWER_BAZOOKA 80
#define MAXHP_BAZOOKA 2000
#define DEFENSE_BAZOOKA 1
#define SPEED_BAZOOKA 2
#define A_TYPE_BAZOOKA ALL
#define COST_BAZOOKA 50
#define CLK_BAZOOKA 120
#define A_FREQ_BAZOOKA 13
/*セグウェイ兵*/
#define POWER_SEGWAY 90
#define MAXHP_SEGWAY 1500
#define DEFENSE_SEGWAY 2
#define SPEED_SEGWAY 3
#define A_TYPE_SEGWAY RAND
#define COST_SEGWAY 30
#define CLK_SEGWAY 80
#define A_FREQ_SEGWAY 50

/*幼女*/
#define POWER_YOUJO 200
#define MAXHP_YOUJO 2000
#define DEFENSE_YOUJO 1
#define SPEED_YOUJO 5
#define A_TYPE_YOUJO RAND
#define COST_YOUJO 500
#define CLK_YOUJO 200
#define A_FREQ_YOUJO 50

/*盾篭り*/
#define POWER_TATEKO 0
#define MAXHP_TATEKO 3000
#define DEFENSE_TATEKO 2
#define SPEED_TATEKO 3
#define A_TYPE_TATEKO RAND
#define COST_TATEKO 400
#define CLK_TATEKO 200
#define A_FREQ_TATEKO 0

/*姫騎士*/
#define POWER_HIME 50
#define MAXHP_HIME 3000
#define DEFENSE_HIME 2
#define SPEED_HIME 3
#define A_TYPE_HIME RAND
#define COST_HIME 400
#define CLK_HIME 200
#define A_FREQ_HIME 12

/*イカロス*/
#define POWER_IKAROS 10
#define MAXHP_IKAROS 3000
#define DEFENSE_IKAROS 2
#define SPEED_IKAROS 3
#define A_TYPE_IKAROS ALL
#define COST_IKAROS 400
#define CLK_IKAROS 200
#define A_FREQ_IKAROS 2

/*マジョ*/
#define POWER_MAJO 150
#define MAXHP_MAJO 700
#define DEFENSE_MAJO 0
#define SPEED_MAJO 3
#define A_TYPE_MAJO RAND
#define COST_MAJO 400
#define CLK_MAJO 200
#define A_FREQ_MAJO 152

/*戦車*/
#define POWER_TANK 25
#define MAXHP_TANK 1200
#define DEFENSE_TANK 1
#define SPEED_TANK 2
#define A_TYPE_TANK RAND
#define COST_TANK 10
#define CLK_TANK 120
#define A_FREQ_TANK 91

/*ゲッコー*/
#define POWER_GEKKO 7
#define MAXHP_GEKKO 1800
#define DEFENSE_GEKKO 0
#define SPEED_GEKKO 2
#define A_TYPE_GEKKO ALL
#define COST_GEKKO 30
#define CLK_GEKKO 120
#define A_FREQ_GEKKO 0

/*レールガン*/
#define POWER_RAILGUN 1500
#define MAXHP_RAILGUN 8000
#define DEFENSE_RAILGUN 2
#define SPEED_RAILGUN 1
#define A_TYPE_RAILGUN NOATK
#define COST_RAILGUN 0
#define CLK_RAILGUN 120
#define A_FREQ_RAILGUN 300

/*ヘリ*/
#define POWER_COPTER 200
#define MAXHP_COPTER 800
#define DEFENSE_COPTER 1
#define SPEED_COPTER 2
#define A_TYPE_COPTER RAND
#define COST_COPTER 50
#define CLK_COPTER 120
#define A_FREQ_COPTER 351




#define STAGE1_W 1950
#define STAGE2_W STAGE1_W+2200
#define STAGE3_W STAGE2_W+2500
#define STAGE4_W STAGE3_W+3000
#define STAGE5_W STAGE4_W+3200
#define STAGE6_W STAGE5_W+3500
#define STAGE7_W STAGE6_W+4000
#define STAGE8_W STAGE7_W+4700